### ISSUE TITLE
SQL File

### ISSUE THREAD

**Issue by emresaracoglu** [dengsauve/Basic-Flashcards#1]
Hi,

Thank you for repo, I didn't find SQL file, can you upload?

**Comment by dengsauve** [comment]
@emresaracoglu hello! 

Please copy `include/example.env.php` to `include/env.php`.

Then, in `include/env.php`, you can specify strings for:

- `$servername`
- `$username`
- `$password`
- `$dbname`

You can specify `$debug` as true/false here as well. 

I apologize for the unconventional structure, this was quick code I made for prototyping an idea I had. I'll revisit and include a better README when time allows.

**Comment by dengsauve** [comment]
It occurred to me you're actually asking for the actual database structure.

I don't have an sql file handy for this, but I can give you the tables you'll need. Here's a list

*flashcards*
- `id`, int, AUTO_INCREMENT, primary key
- `term`, text, not_null
- `definition`, text, not_null
- `question`, text, null

*flashcard_groups*
- `id`, int, AUTO_INCREMENT, primary key
- `flashcard_id`, int, not_null
- `group`, int, not_null

*groups*
- `id`, int, AUTO_INCREMENT, primary key
- `name`, text, not_null

Again, as time permits, I will review and make this more presentable.

**Comment by dengsauve** [comment]
I pulled an auto-generated build SQL script from the server, see `flashcardsdata.sql`

**Comment by emresaracoglu** [comment]
Thank you @dengsauve
